name: paa
channels:
  - defaults
dependencies:
  - python=3.6
  - mpld3
  - scikit-learn
  - matplotlib
  - pandas
  - xlrd
  - openpyxl
  - spyder
  - seaborn
  - pip
  - pip:
    - plotnine
    - adjusttext
    - xlrd
    - fuzzywuzzy
    - python-Levenshtein
    - fastcluster
    - colorama
    - notebook

